# HowYouSeeMe Configuration
system:
  log_level: INFO
  data_dir: "./data"
  cache_dir: "./data/cache"
  
perception:
  kinect:
    device_id: 0
    rgb_resolution: [1920, 1080]
    depth_resolution: [512, 424]
    fps: 30
  
  slam:
    backend: "basic_orb"  # or "rtabmap", "orb_slam3"
    map_frame: "map"
    feature_detector: "ORB"
    max_features: 1000
    
  detection:
    model: "yolov5s"  # Start with small model for testing
    confidence_threshold: 0.5
    nms_threshold: 0.4
    
  hand_tracking:
    model: "mediapipe"
    confidence_threshold: 0.7
    
  face_analysis:
    detection_model: "mtcnn"
    recognition_model: "facenet"
    
resource_management:
  gpu_memory_limit: 6  # GB
  max_concurrent_models: 2
  model_timeout: 30  # seconds
  processing_queue_size: 10

memory:
  redis_host: "localhost"
  redis_port: 6379
  short_term_ttl: 600  # 10 minutes
  long_term_ttl: 86400  # 24 hours
  
mcp:
  host: "0.0.0.0"
  port: 8000
  enable_websockets: true
  max_connections: 10

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/howyouseeme.log"
  max_size: 10485760  # 10MB
  backup_count: 5